services:
  api:
    build:
      context: ./packages/api
    command: yarn ts-node-dev --interval 1000 --respawn --transpile-only -r tsconfig-paths/register --ignore-watch node_modules src/main.ts
    user: "root"
    volumes:
      - ./packages/api:/usr/src/app
      - api_build:/usr/src/app/dist
  web:
    build:
      context: ./packages/web
    command: yarn dev
    volumes:
      - ./packages/web:/usr/src/app
      - web_node_modules:/usr/src/app/node_modules
      - web_build:/usr/src/app/.next
  postgres:
    ports:
      - 5432:5432
  redis:
    ports:
      - 6379:6379
