import React, { useState } from 'react';
import { Check, Copy, KeyRound } from 'lucide-react';

import { useGetParamsQuery } from '../../utils/graphql';

import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Skeleton } from '@/components/ui/skeleton';

export function ClientApiKeyComponent() {
  const { data, loading } = useGetParamsQuery();
  const [copied, setCopied] = useState(false);
  const apiKey = data?.params?.sonarr_radarr_api_key ?? '';

  const copy = async () => {
    if (!apiKey) return;
    try {
      await navigator.clipboard.writeText(apiKey);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard access can be blocked; the key stays selectable in the input.
    }
  };

  if (loading) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Mediora client</CardTitle>
        </CardHeader>
        <CardContent>
          <Skeleton className="h-9 w-full" />
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <KeyRound className="h-4 w-4" />
          Mediora client
        </CardTitle>
      </CardHeader>
      <CardContent className="flex flex-col gap-3">
        <p className="text-sm leading-6 text-muted-foreground">
          Paste this API key into the Mediora client&apos;s Mediora Server
          settings. It is generated by Mediora Server and stays the same across
          restarts.
        </p>
        <div className="flex items-center gap-2">
          <Input
            readOnly
            value={apiKey}
            className="font-mono"
            onFocus={({ target }) => target.select()}
          />
          <Button type="button" variant="outline" onClick={copy}>
            {copied ? (
              <Check className="h-4 w-4" />
            ) : (
              <Copy className="h-4 w-4" />
            )}
            {copied ? 'Copied' : 'Copy'}
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
