# This workflow will do a clean install of node dependencies, typecheck and build
# both packages across node 22.

name: lint and build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'yarn'
    - run: yarn
    - run: yarn lint
    - run: (cd packages/api && yarn build)
    - run: (cd packages/api && yarn test:cov)
    - run: (cd packages/web && yarn test)
    - run: (cd packages/web && yarn typecheck && yarn build)
